name: Ping
version: '${project.version}'
main: org.timsplugins.ping.ServerPlugin
api-version: '1.20'
load: STARTUP
commands:
  ping:
    usage: /<command>
    description: Gibt dir deinen aktuellen Ping zum Server zurück
  firework:
    usage: /<command>
    description: Zündet eine Rakete in deiner Blickrichtung oder in Richtung der Gegebenen Koordinaten
  setWayPoint:
    usage: /<command>
    description: Setzt einen WegPunkt

